### ISSUE TITLE
Give `ServerId` a custom `Debug` implementation

### ISSUE THREAD

**Issue by 8573** [8573/irc-bot.rs#32]
Give `ServerId` a custom `Debug` implementation that displays the server UUID in "hyphenated" form rather than as a list of `u8` values.

**Comment by 8573** [comment]
Once that's done, change the uses of `server_id.uuid.hyphenated()` to use this `Debug` implementation instead.

**Comment by jxhn** [comment]
Does 6a304ae97cca41dd1da0ffbecb2d1ac7836ce98c mean this is closed @8573? Wanted to contribute to the project to help myself learn Rust and only found that commit _after_ writing the thing 🤦‍♂️

**Comment by 8573** [comment]
> Does 6a304ae mean this is closed @8573?

It indeed would appear to, yes. Thanks for your interest in the crate; my apologies for apparently forgetting that I had filed an issue ticket about this.
